version: "3.7"

services:
  php-8.1:
    build:
      context: .
      args:
        PHP_VERSION: 8.1
  php-8.2:
    build:
      context: .
      args:
        PHP_VERSION: 8.2
  php-8.3:
    build:
      context: .
      args:
        PHP_VERSION: 8.3
  php-8.4:
    build:
      context: .
      args:
        PHP_VERSION: 8.4-rc
