version: "3.6"

services:
  php-7.1:
    build:
      context: .
      args:
        PHP_VERSION: 7.1
  php-7.2:
    build:
      context: .
      args:
        PHP_VERSION: 7.2
  php-7.3:
    build:
      context: .
      args:
        PHP_VERSION: 7.3

  php-7.4:
    build:
      context: .
      args:
        PHP_VERSION: 7.4.0RC1
